# Generated by Django 4.0.1 on 2022-01-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager_app', '0002_participant_rename_email_event_hostemail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='registerby',
        ),
        migrations.AddField(
            model_name='event',
            name='endTime',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='event',
            name='registerbyDate',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='event',
            name='registerbyTime',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='event',
            name='startTime',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='event',
            name='endDate',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='event',
            name='hostEmail',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='event',
            name='startDate',
            field=models.DateField(default=None),
        ),
    ]
