# Generated by Django 4.0.1 on 2022-01-21 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager_app', '0003_remove_event_registerby_event_endtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='event_manager_app.event'),
        ),
        migrations.AddField(
            model_name='participant',
            name='participantCount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='participant',
            name='registerType',
            field=models.CharField(default=None, max_length=12),
        ),
    ]
